CC	= g++
RM	= rm -rf

LDFLAGS		+= -ljsoncpp -ldl -lpthread
CXXFLAGS	+= -W -Wall -Wextra -Iinc

SRCS		= src/main.cpp \
	src/Main.cpp \
	src/Config.cpp \
	src/ModuleManager.cpp \
	src/socket/Handler.cpp \
	src/socket/Listener.cpp \
	src/socket/Reactor.cpp \
	src/socket/Session.cpp \
	src/socket/Stream.cpp \
	src/http/HttpParser.cpp \
	src/Server.cpp \
	src/DynLib.cpp \
	src/LibManager.cpp
	src/ModuleLog.cpp
